### ISSUE TITLE
STARTLS not working

### ISSUE THREAD

**Issue by frankhdz** [benmerckx/smtpmailer#1]
This is more of a question. How to you send an email using STARTLS or SSL? When I set 

`secure:StartTls;`

I get the error
`Something went wrong: Not supported on this platform`

How do you properly set this? I am trying to send an email via smtp.gmail.com.

**Comment by benmerckx** [comment]
Which haxe version are you using, and which target are you compiling to?

**Comment by frankhdz** [comment]
Compiling to Mac and Windows haxe version 3.4.0

**Comment by benmerckx** [comment]
Assuming you're targeting hxcpp, this library depends on asys which had no support for the newer ssl sockets in haxe 3.3+. For now [I've added support](https://github.com/benmerckx/asys/commit/629c71ce0d42830f2f86f90fe0bf3778544d471b) for creating secure sockets, but don't have time to figure out the upgrading (starttls) part yet. But since gmail supports sending mail via ssl (on port 465) you should be able to send mails if you install asys via [`haxelib git`](https://lib.haxe.org/documentation/using-haxelib/#git).

**Comment by benmerckx** [comment]
This is fixed with smtpmailer 0.1.0 and asys 0.3.0. Using ssl/starttls is now supported on java, php, nodejs, neko and cpp.
